---
apiVersion: v1
kind: Pod
metadata:
  name: my-flask
  labels:
    app: flask-web
spec:
  containers:
    - image: yishaiz/webserver:v1.2
      name: flask
      ports:
      - containerPort: 5000
        name: http
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:  
  name: opsschool-service
spec:
  selector:    
    app: flask-web
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30036
    protocol: TCP

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: my-app
  template:
    metadata:
      labels:
        name: my-app
    spec:
      containers:
      - name: my-app
        image: yishaiz/webserver:v1.2
        ports:
        - containerPort: 5000




        # port: 8081
        # targetPort: 8081


  # containers:
  #   - image: yishaiz/webserver:v1.2
  #     ports:  
  #     - name: http
  #       port: 8081
  #     targetPort: 5000
  #     protocol: TCP



  # containers:
  # - name: front-end
  #   image: yishaiz/webserver:v1.2
  #   ports:
  #   - port: 5000
  #     containerPort: 8081